"""Storage contracts for governance artifacts (memory and SQLite implementations)."""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional, Protocol

from ..domain import (
    ApprovalRequestRecord,
    AuditRecord,
    CandidateActionSetRecord,
    DecisionRecord,
    ExecutionRecord,
    GovernanceProposalRecord,
    InstitutionalDecisionRecord,
)


class AuditStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: AuditRecord) -> None: ...
    def get(self, audit_id: str) -> Optional[AuditRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class ProposalStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: GovernanceProposalRecord) -> None: ...
    def get(self, proposal_id: str) -> Optional[GovernanceProposalRecord]: ...
    def find_by_content_proposal_id(self, content_proposal_id: str) -> List[GovernanceProposalRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class DecisionStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: DecisionRecord) -> None: ...
    def get(self, record_id: str) -> Optional[DecisionRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class ExecutionStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: ExecutionRecord) -> None: ...
    def get(self, record_id: str) -> Optional[ExecutionRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class ApprovalStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: ApprovalRequestRecord) -> None: ...
    def get(self, record_id: str) -> Optional[ApprovalRequestRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class CandidateSetStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: CandidateActionSetRecord) -> None: ...
    def get(self, record_id: str) -> Optional[CandidateActionSetRecord]: ...

    @staticmethod
    def now() -> datetime: ...


class InstitutionStoreProtocol(Protocol):
    def new_id(self) -> str: ...
    def put(self, record: InstitutionalDecisionRecord) -> None: ...
    def get(self, record_id: str) -> Optional[InstitutionalDecisionRecord]: ...

    @staticmethod
    def now() -> datetime: ...
